---
pagetitle: Research
---

<link rel="stylesheet" href="styles.css" type="text/css">

### Research papers

**[Quid pro quo: the institutional environment and the allocation of household wealth](http://dspace.library.uu.nl/handle/1874/394040)** U.S.E. Research Institute Working Paper Series 19-25.

What can account for the allocation of household wealth? In this paper I analyse the evolution of the French and Dutch household portfolio between 1963 and today. I employ a Financial Almost Ideal Demand System to estimate wealth and interest rate elasticities for five wealth classes: M1, Savings, Equity, Life-insurance and housing wealth. My main contribution is that I highlight the importance of the institutional environment for the allocation of household wealth. The liberalization wave of French finance in the 1980s is reflected in the estimated elasticities, which increase in size for those assets that became more widely available. Institutional change in the Netherlands was much more limited, which is reflected in the relative stability of the estimated interest and wealth elasticities.

**Explaining financial system dynamics: a new institutional framework**

The financial service provision to households underwent considerable change since the late 1960s but our understanding of this process trails behind. Competing explanations from a cultural, legal and political economy perspective made important contributions but remain heavily entrenched. This paper proposes an analytical framework on the basis of Williamson (2000) and the three strands of literature, which facilitates the study of the evolution of the financial service provision to households over time. The utility of the framework is illustrated by means of a comparative case study of the introduction of the Second Banking Directive in the context of French and Dutch retail finance. I show that the imposition of a single formal rule on two otherwise different systems of retail finance need not necessarily contribute to their financial integration.


### Work in progress

**Coping with financial fragility: the case of the Dutch Great Depression** (with Oscar Gelderblom)

The financial crisis of 2007/8 hit Dutch households hard. Unemployment, problematic debts, and the steep decline of housing prices exposed the financial vulnerability of up to twenty per cent of Dutch households. This paper offers a new historical perspective on the financial vulnerability of households and the possible means to reduce it. We do so with a fine-grained empirical analysis of Dutch household financial behaviour in the aftermath of the biggest financial crisis in modern history, the Great Depression of the 1930s. We employ a 1935 survey among 598 households and study the determinants of household financial fragility and household coping mechanisms. We identify social networks and household savings as important coping mechanisms for households in financial distress.

**The evolution of household wealth in the Netherlands 1850-2019** (with Amaury de Vicq and Michail Moatsos) 

In this paper we use a novel approach and previously underexplored sources to reconstruct the evolution and composition of household wealth in the Netherlands between the 1850s and 2020. For the earlier period (i.e. 1850s-1960s) we rely on records of inheritance taxation, where for the later period (1970-2018) we employ national accounts data and earlier statistical studies. Preliminary results indicate two notable shifts. First, while in the early period, households on the aggregate level clearly preferred to invest in foreign assets over domestic assets, this preference shifted drastically during the first world war. Second, the introduction of a capital funded pension system in the 1950s appears to have crowded out sizeable investment in marketable instruments up to that point. Apart from that, changes in the allocation of household wealth are remarkably minor over a period of more than 150 years.

### Publications
**[De erfenis als bron](https://www.vangennep-boeken.nl/boek_detail.php?id=538).** In De Beer, P., Van der Meer, J., Plantenga, J., Salverda, W. (Eds.), Voor wie is de erfenis? (pp. 121-134). Van Gennep (Amsterdam).

In his seminal study, Wilterdink (1991) shows a considerable degree of wealth inequality in the Netherlands by the end of the 19th century. In this chapter I show that this inequality was largely of historical origin. I employ a set of 2586 probate inventories dated between 1625-1899 that record all financial and non-financial assets and liabilities. By linking the over 600 thousand individual items to various economic strata I discuss the evolution of wealth inequality over the 17th-19th century. 