---
pagetitle: Talks
---
<link rel="stylesheet" href="styles.css" type="text/css">

### Conferences and seminars

* Finance and History Workshop, Radboud University Nijmegen (upcoming)

* Datini-ESTER Advanced workshop, Istituto Internazionale di Storia Economica "F. Datini" (upcoming)

* De Zichtbare Hand, Utrecht University (30-08-2019)

* Financing the real economy - Echoes from the past workshop, Utrecht University (16-04-2019)

* LSE Graduate seminar (28-08-2018)

* Graduate seminar, Banque de France (22-04-2018)

* Groningen FRESH meeting (01-12-2018)

* De Nederlandsche Bank (18-10-2018)

* 2018 Masterclass with Geoffrey Jones, Technical University Eindhoven (21-06-2018)

* World Economic History Congress, Boston (06-08-2018)

* Financial History Workshop, Université Libre de Bruxelles (06-06-2018)

* University of Groningen (27-02-2018)

* WEHC pre-conference, Banque de France (04-04-2018)

* Banque de France graduate seminar (23-05-2017)

* Economic History Society residential training course, Manchester University (23-11-2017).

* ESTER Research Design Course, University of Pisa (18-10-2016)

* Financial History Workshop, Tilburg University (24-6-2016)